import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { isIP } from 'node:net';
import { join } from 'node:path';
import { writeSecretFile } from '../config/paths.js';

/** Everything that goes into data/livekit.yaml (spec §8.1). */
export interface LivekitConfigInput {
  /** Internal signaling/API port, bound to 127.0.0.1 only. */
  port: number;
  /** Public UDP port for all media (mux). */
  udpPort: number;
  /** Public ICE-TCP port. */
  tcpPort: number;
  /** The IP LiveKit announces in its ICE candidates. */
  nodeIp: string;
  apiKey: string;
  apiSecret: string;
  /** http://127.0.0.1:<internal port>/livekit/webhook */
  webhookUrl: string;
}

const TOKEN_CHARS = /^[A-Za-z0-9_-]{8,128}$/;

function port(n: number, name: string): number {
  if (!Number.isInteger(n) || n < 1 || n > 65535) throw new Error(`${name} must be a port number (1-65535)`);
  return n;
}

/**
 * The LiveKit YAML with ONLY keys verified against livekit-server 1.13.7 (spec §8.1):
 * it parses the file in strict mode and aborts on any unknown key. Every value is a
 * validated number or a JSON-quoted string (valid YAML), so nothing can inject keys.
 *
 * - `bind_addresses` limits the signaling port to loopback: only the /rtc proxy reaches it.
 * - `use_external_ip: false` + explicit `node_ip`: no STUN to Google/Twilio at boot, and
 *   LiveKit still starts without internet (spec §4 "sem terceiros").
 * - `advertise_internal_ip: true` keeps LAN/VPN candidates next to `node_ip`.
 */
export function renderLivekitConfig(c: LivekitConfigInput): string {
  if (isIP(c.nodeIp) === 0) throw new Error('nodeIp must be an IP address');
  if (!TOKEN_CHARS.test(c.apiKey) || !TOKEN_CHARS.test(c.apiSecret)) throw new Error('invalid LiveKit API credentials');
  if (!/^http:\/\/127\.0\.0\.1:\d{1,5}\/livekit\/webhook$/.test(c.webhookUrl)) throw new Error('the webhook must be a loopback URL');
  const q = (s: string) => JSON.stringify(s);
  return [
    '# Generated by GhostLink on every start (spec §8.1). Do not edit: LiveKit refuses unknown keys.',
    `port: ${port(c.port, 'port')}`,
    'bind_addresses:',
    `  - ${q('127.0.0.1')}`,
    'rtc:',
    `  udp_port: ${port(c.udpPort, 'udpPort')}`,
    `  tcp_port: ${port(c.tcpPort, 'tcpPort')}`,
    '  use_external_ip: false',
    `  node_ip: ${q(c.nodeIp)}`,
    '  advertise_internal_ip: true',
    'keys:',
    `  ${q(c.apiKey)}: ${q(c.apiSecret)}`,
    'webhook:',
    `  api_key: ${q(c.apiKey)}`,
    '  urls:',
    `    - ${q(c.webhookUrl)}`,
    '',
  ].join('\n');
}

/** Writes data/livekit.yaml readable by the owner only (spec §7: 0600). */
export function writeLivekitConfig(dataDir: string, c: LivekitConfigInput): string {
  const path = join(dataDir, 'livekit.yaml');
  writeSecretFile(path, renderLivekitConfig(c));
  return path;
}

export interface LivekitKeys {
  apiKey: string;
  apiSecret: string;
}

/**
 * The LiveKit API key and secret, generated on the first run and kept in
 * data/livekit-keys.json (0600). The secret is 256 bits: it signs every voice
 * token and authenticates the webhooks, and the /rtc proxy checks tokens with it.
 */
export function loadOrCreateLivekitKeys(dataDir: string): LivekitKeys {
  const path = join(dataDir, 'livekit-keys.json');
  if (existsSync(path)) {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as Partial<LivekitKeys>;
    if (typeof parsed.apiKey === 'string' && typeof parsed.apiSecret === 'string' && TOKEN_CHARS.test(parsed.apiKey) && TOKEN_CHARS.test(parsed.apiSecret) && parsed.apiSecret.length >= 32) {
      return { apiKey: parsed.apiKey, apiSecret: parsed.apiSecret };
    }
    throw new Error(`${path} is corrupt; delete it to generate new LiveKit keys`);
  }
  const keys: LivekitKeys = { apiKey: `GL${randomBytes(12).toString('base64url')}`, apiSecret: randomBytes(32).toString('base64url') };
  writeSecretFile(path, `${JSON.stringify(keys, null, 2)}\n`);
  return keys;
}
