/**
 * The pencil on shared screens (spec 2026-10-01-lapis-na-tela-design.md): who watches a screen,
 * and who shares it, draw strokes that fade after ~3 s. The strokes go through the GhostLink
 * server (never LiveKit's data channel), which stores nothing. Payloads, events, strict server
 * schemas and lenient client schemas.
 */
import { z } from 'zod';
import { voiceChannelIdSchema } from './voice.js';

/** The `features` flag of a server that relays strokes (spec §1: old servers have no pencil). */
export const FEATURE_SCREEN_DRAW = 'screenDraw';

export const SCREEN_DRAW_LIMITS = {
  /** Points in one batch (spec §3). */
  maxPoints: 64,
  /** A stroke id is generated by the app and short. */
  strokeIdMaxLength: 32,
  /** Batches per person per second; above it they are dropped without an error (spec §3). */
  batchesPerSecond: 30,
  /** "Permitir desenhos" changes per sharer. */
  allowPerWindow: 10,
  allowWindowMs: 10_000,
} as const;

/** A point in the video frame, both coordinates from 0 to 1 (the `contain` letterbox excluded). */
export type DrawPoint = [x: number, y: number];

/** `screen.draw` request: one batch of a stroke on `sharerId`'s screen. */
export interface ScreenDrawPayload {
  channelId: string;
  sharerId: string;
  /** Generated by the app; the same for every batch of one stroke. */
  strokeId: string;
  points: DrawPoint[];
  /** The stroke's last batch. */
  end: boolean;
}

/** `screen.draw` event, to the others in the voice channel. */
export interface ScreenDrawEvent extends ScreenDrawPayload {
  /** Who drew it. */
  userId: string;
}

/** `screen.drawAllow` request: the sharer turns "Permitir desenhos" on or off for their share. */
export interface ScreenDrawAllowPayload {
  channelId: string;
  allow: boolean;
}

/** `screen.drawAllow` event, to everyone who can see the channel. */
export interface ScreenDrawAllowEvent {
  channelId: string;
  sharerId: string;
  allow: boolean;
}

/** A share where drawing is off. */
export interface ScreenDrawShare {
  channelId: string;
  sharerId: string;
}

/** The welcome's `screenDraw` field: the shares this session can see where drawing is off. */
export interface ScreenDrawWelcome {
  disallowed: ScreenDrawShare[];
}

const USER_ID = /^[0-9a-f]{32}$/;
const STROKE_ID = new RegExp(`^[A-Za-z0-9_-]{1,${SCREEN_DRAW_LIMITS.strokeIdMaxLength}}$`);

const coordinate = z.number().min(0).max(1);
/** Exactly [x, y]: z.tuple refuses a third element. */
export const drawPointSchema: z.ZodType<DrawPoint> = z.tuple([coordinate, coordinate]);
const pointsSchema = z.array(drawPointSchema).min(1).max(SCREEN_DRAW_LIMITS.maxPoints);
const userIdSchema = z.string().regex(USER_ID);
const strokeIdSchema = z.string().regex(STROKE_ID);

// ---- server side: strict (spec §5.1) ----

export const screenDrawSchema = z.strictObject({
  channelId: voiceChannelIdSchema,
  sharerId: userIdSchema,
  strokeId: strokeIdSchema,
  points: pointsSchema,
  end: z.boolean(),
});

export const screenDrawAllowSchema = z.strictObject({ channelId: voiceChannelIdSchema, allow: z.boolean() });

// ---- client side: z.object drops unknown keys ----

export const screenDrawEventSchemaClient: z.ZodType<ScreenDrawEvent> = z.object({
  channelId: voiceChannelIdSchema,
  sharerId: userIdSchema,
  userId: userIdSchema,
  strokeId: strokeIdSchema,
  points: pointsSchema,
  end: z.boolean(),
});

export const screenDrawAllowEventSchemaClient: z.ZodType<ScreenDrawAllowEvent> = z.object({
  channelId: voiceChannelIdSchema,
  sharerId: userIdSchema,
  allow: z.boolean(),
});

const shareSchemaClient = z.object({ channelId: voiceChannelIdSchema, sharerId: userIdSchema });

export const screenDrawWelcomeSchemaClient: z.ZodType<ScreenDrawWelcome> = z.object({
  disallowed: z.array(shareSchemaClient).max(1_000),
});
